### ISSUE TITLE
rgw_port ignored in ceph.conf.rgw, prevents co-locating openattic and rgw roles

### ISSUE THREAD

**Issue by fghaas** [SUSE/DeepSea#622] opened 2017-09-12 14:01 UTC
_(Disclaimer: I'm new to DeepSea and may be misunderstanding how things are supposed to work. Seen on SES5 Beta 10.)_
* * *
The documentation doesn't seem state that the `openattic` and `rgw` roles can't be colocated, but it appears that they can't be made to install on the same node.

```
 # salt-run state.orch ceph.stage.services
openattic                : ['rgw port conflicts with openATTIC on deploy.example.com - check ceph.conf']
```

This warning comes from `srv/modules/runners/validate.py`, which contains:

```python
    def openattic(self):
        """
        Check for incompatible issues for openATTIC

        The rgw role (or any custom rgw role) may be configured to use
        port 80.  With all the configuration allowed in the pillar, checking the
        final ceph.conf seems the most reliable.
        """
```

The only configuration variable I've been able to dig up that fits the bill would be `rgw_port`, but sadly that seems to be ignored in `srv/salt/ceph/configuration/files/ceph.conf.rgw`, which contains:

```
[client.{{ client }}]
rgw frontends = "civetweb port=80"
rgw dns name = {{ fqdn }}
```

Unfortunately, it appears impossible to override this in `/srv/salt/ceph/configuration/files/ceph.conf.d/client.conf`, because that just makes *both* entries (with `port=80` and `port=<someotherport>`) pop up in `ceph.conf`. Funnily enough, radosgw itself would use the latter (correct) entry, but the sanity check in `validate.py` just does a regex match on the whole file, and the deployment breaks.

* * *
I _think_ what needs changing here is that `ceph.conf.rgw` should say `"civetweb port= {{ rgw_port }}"`, but as I said, I might be misunderstanding something.

**Comment by swiftgist** [comment] 2017-09-12 16:21
Hi Florian,
  This is fixed with https://github.com/SUSE/DeepSea/pull/604, but has not been built yet.  This will be in deepsea 0.7.27, Milestone 13, Beta 11.

  The short issue is changes to simplify network reconfiguration caused a cascading effect from ceph.conf to RGW to assumptions about openATTIC and RGW conflicts.  The validation was intended to prevent an admin from assigning openATTIC and RGW on the same node both using port 80.  Otherwise, one fails somewhat mysteriously.

**Comment by fghaas** [comment] 2017-09-12 17:27
I see — sorry for the duplicate; it would appear I missed this since there was neither an open issue nor an open PR.

However, it would seem to my that even with #604 `rgw_port` can't be used to make rgw listen on a different port, or can it?

**Comment by theanalyst** [comment] 2017-09-12 17:58
So let me see if I understand this correctly, the situation you're describing is that instead of the port in rgw_frontends, just the value of `rgw_port` being set in ceph.conf right? 

This isn't handled right now, it shouldn't be too hard to handle that case, though the other corner case you mentioned wherein both `rgw port` and `civetweb port` comes up would most probably be worth a warning, though that might still have funny behaviours in other parts of code that use rgw port, but we should anyway handle the case of `rgw_port` being set in config.

**Comment by fghaas** [comment] 2017-09-12 18:02
Well let me ask this way: if I want radosgw to let civetweb listen on a port other than 80, what is the proper way to do that?

**Comment by theanalyst** [comment] 2017-09-12 18:07
it'd be to set the port as a different value in `srv/salt/ceph/configuration/files/ceph.conf.rgw` (now that I'm seeing it, there would still be an edge case that'll introduce)

**Comment by fghaas** [comment] 2017-09-12 18:14
OK. Didn't know that users were meant to edit that.

**Comment by swiftgist** [comment] 2017-09-12 18:39
Technically, you can but weren't crazy about that either.  We just added #597 which will use your ceph.conf.rgw in .../configuration/files/ceph.conf.d/.  

There's also the possibility of using custom roles.  (That is, creating your own rgw role and creating the two related files.  DeepSea will warn you if they are missing.  This should give an admin the most control of a sophisticated RGW setup, but still use the normal abstraction for assignment/moving etc.)

Yes, we need better documentation. :)

**Comment by fghaas** [comment] 2017-09-13 19:40
@theanalyst I used your method of hacking that file, after which the openattic/rgw colocation worked just fine. Thanks!

That said, @swiftgist I like the new approach. Thanks for putting that in, too!

**Closed** 2017-09-14 19:14 UTC
